package model;

// Generated 2015-7-28 23:22:43 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Container generated by hbm2java
 */
@Entity
@Table(name = "container")
public class Container implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer ownerId;
	private String imageName;
	private String containerId;
	private String hostName;

	public Container() {
	}

	public Container(String name, Integer ownerId, String imageName,
			String containerId, String hostName) {
		this.name = name;
		this.ownerId = ownerId;
		this.imageName = imageName;
		this.containerId = containerId;
		this.hostName = hostName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "owner_id")
	public Integer getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	@Column(name = "image_name", length = 50)
	public String getImageName() {
		return this.imageName;
	}

	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	@Column(name = "container_id", length = 200)
	public String getContainerId() {
		return this.containerId;
	}

	public void setContainerId(String containerId) {
		this.containerId = containerId;
	}

	@Column(name = "host_name", length = 20)
	public String getHostName() {
		return this.hostName;
	}

	public void setHostName(String hostName) {
		this.hostName = hostName;
	}

}
